"""add event color override

Revision ID: 0f0a84349a26
Revises: be83bce50e32
Create Date: 2026-08-02

Adds a nullable per-event colour.

Nullable rather than defaulted on purpose: NULL means "inherit from the
category", and that has to stay distinguishable from a user who deliberately
picked whatever the default would have been. With a default there would be no
way to express "go back to inheriting" once a colour had been set.

Existing events all become NULL, i.e. keep inheriting, which is exactly the
behaviour they had before this column existed.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's AutoString and friends are rendered into autogenerated
# migrations as `sqlmodel.sql.sqltypes.…`, but Alembic's stock template does
# not import the module — so a freshly generated revision raises NameError
# the moment it runs. Imported unconditionally rather than per-revision.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f0a84349a26'
down_revision: Union[str, Sequence[str], None] = 'be83bce50e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('obj_event', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "color",
                sqlmodel.sql.sqltypes.AutoString(length=7),
                nullable=True,
            )
        )


def downgrade() -> None:
    # Drops every per-event colour override. The events survive and fall back
    # to their category colour; only the overrides are lost.
    with op.batch_alter_table("obj_event", schema=None) as batch_op:
        batch_op.drop_column("color")

    # ### end Alembic commands ###
