"""baseline schema

Revision ID: 1ec329c28cf4
Revises: 
Create Date: 2026-08-02 10:20:24.690757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ec329c28cf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obj_calendar',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obj_event_recurence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('days', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.Column('endType', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('until', sa.Integer(), nullable=True),
    sa.Column('estimated_end_date', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obj_event_recurence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obj_event_recurence_id'), ['id'], unique=False)

    op.create_table('obj_user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obj_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obj_user_disabled'), ['disabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_obj_user_username'), ['username'], unique=True)

    op.create_table('lnk_user_calendar',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('right', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['obj_calendar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['obj_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lnk_user_calendar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lnk_user_calendar_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lnk_user_calendar_user_id'), ['user_id'], unique=False)

    op.create_table('obj_category',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=7), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['obj_calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obj_event',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calendar_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_start', sa.Integer(), nullable=False),
    sa.Column('date_end', sa.Integer(), nullable=False),
    sa.Column('category_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reminder', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('recurence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['obj_calendar.id'], ),
    sa.ForeignKeyConstraint(['recurence_id'], ['obj_event_recurence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obj_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obj_event_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_obj_event_date_end'), ['date_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_obj_event_date_start'), ['date_start'], unique=False)

    op.create_table('obj_event_recurrence_exception',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recurrence_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recurrence_id'], ['obj_event_recurence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('obj_event_recurrence_exception', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obj_event_recurrence_exception_recurrence_id'), ['recurrence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('obj_event_recurrence_exception', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obj_event_recurrence_exception_recurrence_id'))

    op.drop_table('obj_event_recurrence_exception')
    with op.batch_alter_table('obj_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obj_event_date_start'))
        batch_op.drop_index(batch_op.f('ix_obj_event_date_end'))
        batch_op.drop_index(batch_op.f('ix_obj_event_calendar_id'))

    op.drop_table('obj_event')
    op.drop_table('obj_category')
    with op.batch_alter_table('lnk_user_calendar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lnk_user_calendar_user_id'))
        batch_op.drop_index(batch_op.f('ix_lnk_user_calendar_calendar_id'))

    op.drop_table('lnk_user_calendar')
    with op.batch_alter_table('obj_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obj_user_username'))
        batch_op.drop_index(batch_op.f('ix_obj_user_disabled'))

    op.drop_table('obj_user')
    with op.batch_alter_table('obj_event_recurence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obj_event_recurence_id'))

    op.drop_table('obj_event_recurence')
    op.drop_table('obj_calendar')
    # ### end Alembic commands ###
