"""add lnk user calendar rank

Revision ID: 5af4877c20af
Revises: 0f0a84349a26
Create Date: 2026-09-12 13:33:33.203519

Adds a per-membership `rank` column to lnk_user_calendar so calendar order
in the sidebar is a per-user preference (see reorder_calendars in
lnk_user_calendar_service.py) rather than a single global order on
obj_calendar — two users sharing a calendar can each keep it in a different
position in their own list.

Existing rows are backfilled with sequential ranks per user, ordered by
rowid (their original insertion order), so upgrading doesn't reshuffle
anyone's current calendar order. New memberships get the next rank for
their user (see _next_rank), so newly created/joined calendars land at the
end of the list instead of colliding at 0.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# SQLModel's AutoString and friends are rendered into autogenerated
# migrations as `sqlmodel.sql.sqltypes.…`, but Alembic's stock template does
# not import the module — so a freshly generated revision raises NameError
# the moment it runs. Imported unconditionally rather than per-revision.
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5af4877c20af'
down_revision: Union[str, Sequence[str], None] = '0f0a84349a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('lnk_user_calendar', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('rank', sa.Integer(), nullable=False, server_default='0')
        )

    conn = op.get_bind()
    user_ids = conn.execute(
        sa.text("SELECT DISTINCT user_id FROM lnk_user_calendar")
    ).scalars().all()

    for user_id in user_ids:
        rows = conn.execute(
            sa.text(
                "SELECT id FROM lnk_user_calendar WHERE user_id = :u ORDER BY rowid"
            ),
            {"u": user_id},
        ).fetchall()
        for rank, (link_id,) in enumerate(rows):
            conn.execute(
                sa.text("UPDATE lnk_user_calendar SET rank = :r WHERE id = :i"),
                {"r": rank, "i": link_id},
            )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('lnk_user_calendar', schema=None) as batch_op:
        batch_op.drop_column('rank')
